
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qafuudhdqzyloawsoexd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhZnV1ZGhkcXp5bG9hd3NvZXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyODUzMjQsImV4cCI6MjA1Njg2MTMyNH0.LSJCHfFkOpSgS74cpa_QWJhVU5DfOTWuBb1bNxjtM4E";

// Use the types from the automatically generated types.ts file
// We're not creating a custom type here as it was causing type conflicts

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
