
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qafuudhdqzyloawsoexd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhZnV1ZGhkcXp5bG9hd3NvZXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyODUzMjQsImV4cCI6MjA1Njg2MTMyNH0.LSJCHfFkOpSgS74cpa_QWJhVU5DfOTWuBb1bNxjtM4E";

// Extend the Database type to include our tables
export interface CustomDatabase extends Database {
  public: {
    Tables: {
      stocks: {
        Row: {
          id: string;
          symbol: string;
          company_name: string;
          sector: string | null;
          industry: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          symbol: string;
          company_name: string;
          sector?: string | null;
          industry?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          symbol?: string;
          company_name?: string;
          sector?: string | null;
          industry?: string | null;
          created_at?: string | null;
        };
      };
      stock_prices: {
        Row: {
          id: string;
          stock_id: string;
          date: string;
          open_price: number;
          close_price: number;
          high_price: number;
          low_price: number;
          volume: number;
          previous_close_price: number | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          stock_id: string;
          date: string;
          open_price: number;
          close_price: number;
          high_price: number;
          low_price: number;
          volume: number;
          previous_close_price?: number | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          stock_id?: string;
          date?: string;
          open_price?: number;
          close_price?: number;
          high_price?: number;
          low_price?: number;
          volume?: number;
          previous_close_price?: number | null;
          created_at?: string | null;
        };
      };
      mutual_funds: {
        Row: {
          id: string;
          fund_house: string;
          fund_name: string;
          category: string;
          risk_level: string;
          fund_size: number;
          launch_date: string | null;
          expense_ratio: number | null;
          alpha: number | null;
          beta: number | null;
          sharpe_ratio: number | null;
          standard_deviation: number | null;
          tracking_error: number | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          fund_house: string;
          fund_name: string;
          category: string;
          risk_level: string;
          fund_size: number;
          launch_date?: string | null;
          expense_ratio?: number | null;
          alpha?: number | null;
          beta?: number | null;
          sharpe_ratio?: number | null;
          standard_deviation?: number | null;
          tracking_error?: number | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          fund_house?: string;
          fund_name?: string;
          category?: string;
          risk_level?: string;
          fund_size?: number;
          launch_date?: string | null;
          expense_ratio?: number | null;
          alpha?: number | null;
          beta?: number | null;
          sharpe_ratio?: number | null;
          standard_deviation?: number | null;
          tracking_error?: number | null;
          created_at?: string | null;
        };
      };
      fund_performance: {
        Row: {
          id: string;
          fund_id: string;
          date: string;
          nav: number;
          benchmark_value: number | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          fund_id: string;
          date: string;
          nav: number;
          benchmark_value?: number | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          fund_id?: string;
          date?: string;
          nav?: number;
          benchmark_value?: number | null;
          created_at?: string | null;
        };
      };
      fund_composition: {
        Row: {
          id: string;
          fund_id: string;
          asset_type: string;
          percentage: number;
          date: string;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          fund_id: string;
          asset_type: string;
          percentage: number;
          date: string;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          fund_id?: string;
          asset_type?: string;
          percentage?: number;
          date?: string;
          created_at?: string | null;
        };
      };
      fund_metrics: {
        Row: {
          id: string;
          fund_id: string;
          date: string;
          returns_1y: number;
          returns_3y: number;
          returns_5y: number;
          risk_score: number;
          volatility: number;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          fund_id: string;
          date: string;
          returns_1y: number;
          returns_3y: number;
          returns_5y: number;
          risk_score: number;
          volatility: number;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          fund_id?: string;
          date?: string;
          returns_1y?: number;
          returns_3y?: number;
          returns_5y?: number;
          risk_score?: number;
          volatility?: number;
          created_at?: string | null;
        };
      };
      fund_alerts: {
        Row: {
          id: string;
          fund_id: string;
          user_id: string;
          alert_type: string;
          threshold: number;
          is_triggered: boolean | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          fund_id: string;
          user_id: string;
          alert_type: string;
          threshold: number;
          is_triggered?: boolean | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          fund_id?: string;
          user_id?: string;
          alert_type?: string;
          threshold?: number;
          is_triggered?: boolean | null;
          created_at?: string | null;
        };
      };
      watchlist: {
        Row: {
          id: string;
          user_id: string;
          stock_id: string;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          stock_id: string;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          stock_id?: string;
          created_at?: string | null;
        };
      };
      price_alerts: {
        Row: {
          id: string;
          user_id: string;
          stock_id: string;
          target_price: number;
          alert_type: string;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          stock_id: string;
          target_price: number;
          alert_type: string;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          stock_id?: string;
          target_price?: number;
          alert_type?: string;
          created_at?: string | null;
        };
      };
      portfolio: {
        Row: {
          id: string;
          user_id: string;
          stock_id: string;
          quantity: number;
          average_price: number;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          stock_id: string;
          quantity: number;
          average_price: number;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          stock_id?: string;
          quantity?: number;
          average_price?: number;
          created_at?: string | null;
        };
      };
    };
    Views: Database['public']['Views'];
    Functions: Database['public']['Functions'];
    Enums: Database['public']['Enums'];
    CompositeTypes: Database['public']['CompositeTypes'];
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
