// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhevyihqxegrfmryqdou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxoZXZ5aWhxeGVncmZtcnlxZG91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MDU5MjQsImV4cCI6MjA1NDE4MTkyNH0.gFmHceOU1RDs9yJnVt8hNvJWz9hoRMIAcQDhqy1HwCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);